language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: CbDuTrH5QvNAPNevjFGf7tAlBRsDjBRrc/5bdSJAVNAPWNywqk0rmJXdyEldQ8Tm4CT4LI0cZi2hAss7QXEktQ5wMo5XMLDLVPwlLgpLlqeQhc3SxPn7b851TeP+bM/o1uUiW+fQm0jIYr6u9Zb6b7h8mjZz5q1f2CGacQoqxCaDXSNfA0SWLZSlSKvjwSEY/SWxYhe8Bcf3qrtBsxg6pozMSyDV1wbr1fqb+nZwtczigCyaB67RZnKnUAJ3FrdRf5xjI3hR+hwgvpoAOWrYFlUz/NuBYK6mSUG/HY6wkzt40nTt5qPY1GtgZGwy8BPY3j82r1dsDqCRIfj6CdoYTFfWWemVQd/FVdpBiUG2W/QzmOLqdcgGRIt5cjcs2l0WN2ZDVITfeRwqsPWZ/RCKezaayN0u9fP8XQX72FkqmAFRG1Dh97FHat0CbsSKte/MkPoUQ2pYwmTCNNfsLQ2kz9EJqOXksiDVIekfqf6EMpHL7HP0yVZIuA1PV3Quiz4xDTTowCKkxubsGDI2dAeYr/EBDbiauX5lHCQ62y5maY4X0+niezxD5jdoX9XeGxXRmiJvGOXct1b+9SwfiwC1hT4060tXs5WdJTv7+PT3RJP2mHie0nMwnrI3IGQjPe0GwJRmheh9neIIwYA0g9rK91eiCOhFh+ZerACn4npC8l4=
